### ISSUE TITLE
[2.2.10] Compiling On FreeBSD 13.2 Fails

### ISSUE THREAD

**Issue by oliviahanley** [Netatalk/netatalk#559]
I'm attempting to compile on FreeBSD 13.2-RELEASE (specifically in a jail on TrueNAS Core) and get this error:

```
timelord.c: In function 'main':
timelord.c:249:51: error: invalid operands to binary - (have 'time_t' {aka 'long int'} and 'char * (*)(int,  int)')
  249 |                         mtime = tv.tv_sec + EPOCH - timezone;
      |                                                   ^
      |                                                   |
      |                                                   char * (*)(int,  int)
*** Error code 1
```

Compiling using GCC with pkgconf, avahi, and db5 installed through pkg. Happy to help troubleshoot or provide additional information.

(If it's useful, this also happens with 2.2.9--I'll test other versions as I have time.)

**Comment by rdmark** [comment]
@oliviahanley Thanks for reporting the issue! I *think* this is the same issue that I fixed with https://github.com/Netatalk/netatalk/pull/416 (a few days after 2.2.10 was tagged.)

Would you be able to check out the latest code in https://github.com/Netatalk/netatalk/tree/branch-netatalk-2-3 and see if this works for you?

**Comment by oliviahanley** [comment]
I cloned that branch, ran bootstrap and configure, and got a new error:
```
root@netatalk:~/netatalk # make all
make  all-recursive
Making all in include
Making all in atalk
/bin/sh ../../libtool --mode=execute dtrace -o afp_dtrace.h -h -s ../../include/atalk/afp_dtrace.d
dtrace: failed to compile script ../../include/atalk/afp_dtrace.d: "/usr/lib/dtrace/ipfw.d", line 1: syntax error near "in_addr_t"
*** Error code 1
```

It's possible I'm out of my depth here, so let me know if there's something obvious I'm missing!

(Side note: 2.2.10 builds file with `./configure --enable-timelord=no`, if that's helpful.)

**Comment by rdmark** [comment]
@oliviahanley hm so something might have gotten messed up in your local repo. The `include/atalk/afp_dtrace.d` file belongs to the `main` branch (netatalk 3.x) and should not exist for 2.x. You may want to clean up the local tree and start over:

```
git reset --hard
git clean -dfx
```

Now to get back to the big picture: The last I heard FreeBSD does *not* have support for AppleTalk networking anymore (removed a few years ago.) So even if you build timelord you cannot use it. One FreeBSD, I recommend doing `--disable-ddp --disable-timelord --disable-a2boot` to turn off the entire AppleTalk software suite and get a Netatalk that does only ASIP (TCP/IP stack.)

If you want AppleTalk networking, I recommend either NetBSD or Debian GNU/Linux....

**Comment by oliviahanley** [comment]
Ugh, yes, I 100% cloned the repository and forgot to switch over to branch-netatalk-2.3. My mistake! I can confirm that branch-netatalk-2.3 builds fine on FreeBSD now, so provided you're comfortable this issue can be closed.

I appreciate the note on AppleTalk networking. That's a feature I'm likely going to want to go to use, so I think I'll probably just spin up a NetBSD VM and move on from there. Thanks for your help troubleshooting this, though, and your continued work on this branch.

**Comment by rdmark** [comment]
Thanks for using netatalk! Your support makes it all worth my while.

There are people out there who are tinkering on userland appletalk stacks, so maybe one day FreeBSD will be serving old Macs again.
